### ISSUE TITLE
第一次迭代需求相关文档和模型

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#1]
- [x] 第一次迭代需求文档

- [x] 第一次迭代用例图

- [x] 还有些什么图去了，学过系分的雪敏你想想？补充一下？我有点不太清楚了

**Comment by wuxuemin** [comment]
第一次迭代的需求一并放在需求规格文档中了，还有领域模型图也在问文档中，总的架构图还需讨论补充

**Comment by wuxuemin** [comment]
用例图我画了总的用例析取图
