### ISSUE TITLE
第三次迭代技术文档问题汇总

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#10]
#第三次迭代技术文档问题汇总
这是用来收集第三次迭代技术文档的问题，由于可能设计时存在没有考虑到的方面以及可能隐含一些问题bug，所以大家查看相应的**api文档**和**第三次迭代技术说明文档**和**er图**时如果存在什么问题，请于此处提出，我会在此处进行查看并且反馈修改~
@MichealWind @TXZdream

**Comment by TXZdream** [comment]
建议将用户分级，例如1 2 3等级，并告知如何区分用户，例如，数据库字段的方式，这样做的目的是方便编写一个中间件专门用于权限检查，而不需要每个函数都写一次权限检查
暂时不进行权限问题的检查，等回复之后再考虑

**Comment by TXZdream** [comment]
关于删除活动的问题：活动发布者也应具有删除自己活动的权利

**Comment by iamxiaoyubei** [comment]
1. 不太懂用户分级方便编写一个中间件专门用于权限检查，而不需要每个函数都写一次权限检查的意思
2. 删除活动在群上问了需求说活动发布者不需要删除活动，可以在群上讨论讨论

**Comment by TXZdream** [comment]
中间件在这里就是对每一个http请求进行预处理，这里可以把我们的权限验证写成一个中间件，所有的请求都会经过这个中间件，也就意味着所有的请求都会被这里的中间件检查，只有满足的请求才会被处理，不满足，也就是权限不够的请求会被直接返回401，从而提高效率。
这里引入用户分级也就是为了便于管理，其余的函数只需要专注于业务逻辑即可，不需要考虑权限是否合适，权限的问题专门交给中间件处理，权限不足的请求会被直接剔除。
而不同用户有不同的权限，所以又需要告诉业务逻辑函数具体的请求拥有怎样的权限，从而做出处理。
如此简洁高效的方法，何乐而不为？

**Comment by MichealWind** [comment]
登录API中说登录后返回的json串中包含token的信息，然后后续登录前端检查cookie中的token，这里的cookie的超时时间之类的没有定义额

**Comment by TXZdream** [comment]
cookie不用定义失效时间，你可以查一下jwt，前端可以对jwt的部分内容进行解析，获得过期时间。当然，由于jwt中包含过期时间，所以在一定时间后，jwt可以自己过期，此时前端发来的请求将会收到401回复，因此前端的cookie不用考虑过期，如果必须要加，可以设置成一个月或者怎样的较长时间，这个交给前端控制

**Comment by MichealWind** [comment]
那问一下我们的jwt中的过期时间的字段是啥，exp吗

**Comment by TXZdream** [comment]
是的

**Comment by MichealWind** [comment]
啊还有个问题，登录API那说检查token后，直接传给登录api，这个意思是如果有token的话，访问登录API接口时可以不传账号和密码？

**Comment by TXZdream** [comment]
是的，token如果合法将忽视用户密码，但是后台会对token内包含的用户是否存在进行检查，如果token不合法才会检查用户名密码
其实后台也只知道数据库里面有一个是管理员，具体是谁怎么判断都还是未知，这个要问设计人员

**Comment by TXZdream** [comment]
这些在技术文档都有提到的，可以研究一下

**Comment by MichealWind** [comment]
不能返回一个标识是不是管理员的字段吗

**Comment by TXZdream** [comment]
那这个需要和 @iamxiaoyubei 商量，我们只能在接口上进行商讨，不能私自定下数据格式

**Comment by iamxiaoyubei** [comment]
我开始是想着：token解析后含有用户的account，管理员是有且仅有一个账号，即仅有一个account，因此通过account是不是管理员的那个account（我们会固定一个已知的account如sysuactivity）判断，因为之前打算用token做后端的访问控制，前端每次只传token来；
不过我在新的技术文档中，看到玄昭在后面加了“后台中间件在header中加入X-Role字段，用以表示访问人员的身份”，所以现在后端是已经实现用这个来区分了是吧，我觉得也是可以的，用户如果直接用token自动登陆了，那么后端通过判断token里的account是否管理员来决定在header中加入X-Role，前端传过来的时候也使用X-Role。
你们意见如何？

**Comment by TXZdream** [comment]
话说那个字段仅仅是我在网关中加上的用来向后台的handler传递信息的，从而避免又一次的数据库访问，当然，如果需要这个字段的话，后台加上也不是不可以，但是这个字段只能交给前端用来界面显示的，而后台是不认的，也就是说，这个字段就算加上，也只是为了减轻前端工作量，方便前端渲染界面的，而不是用来作为权限判定的。
建议：在接口文档的返回值header中加上用户的身份标识信息并在技术文档中给出前端和后台所需要的详细说明，包括管理员账户的判定以及这个header字段的不同值所代表的含义。

**Comment by iamxiaoyubei** [comment]
你现在做好的权限控制是根据什么来判定权限的？

**Comment by TXZdream** [comment]
还是token啊，只有token和用户名密码才是唯一可信的，

**Comment by iamxiaoyubei** [comment]
我也觉得直接用token好一些，我写上文档，就说用token进行判定，包括前端和后端，根据刚刚说的那样，可以吧

**Comment by TXZdream** [comment]
恩，所有的header只能用作辅助用途，token这种难以被伪造的才是王道。敏感操作一般都需要进行密码验证，这里先不做，没有那么高的安全级别要求，但是在校内使用，难免有人会破坏，设计上提高警惕还是应该的

**Comment by TXZdream** [comment]
涉及到敏感权限问题的，一定要多加小心，另，建议之后迭代加入图形验证码系统，以解决机器人问题

**Comment by MichealWind** [comment]
刚刚测试登录后的相关api的使用，在Authorization字段的值正确的情况下，获取活动列表的API仍然401了；不知道其他API会不会有一样的问题，是需要别的字段吗？以及JWT中的expires，我这边看值好像不大，所以目测返回的expires是一个时间段畅度而不是一个确定时刻？

**Comment by TXZdream** [comment]
获取活动列表是管理员权限的借口，无法获取很正常，exp就是到期时间点，只需要判定当前时间与之谁打谁小就可以了

**Comment by MichealWind** [comment]
额我意思就是登录了管理员账户后出现了401......exp如果是时间点的话，刚我测试时得到的exp的值很小诶，那个转换成时间点的话是1970年。。。。。

**Comment by TXZdream** [comment]
登录管理员账户我这里使用postman测试过了，是可以拿到token的，而且token在很长一段时间还是有效的

**Comment by TXZdream** [comment]
@MichealWind 你可以去[](http://jwt.calebb.net/)网站上使用得到的token进行解析，上面会显示毫秒级时间的，是没有问题的

**Comment by TXZdream** [comment]
发布活动的pcuser_id可以直接通过后台读取数据库完成，前端是否应该取消id的发送从而确保安全性？ @iamxiaoyubei

**Comment by TXZdream** [comment]
因为后台验证token时本身就可以同时获得用户id，因此并无前端传递id的必要性，而且前端给的信息是不可靠的，因此不建议使用前端给的id

**Comment by TXZdream** [comment]
用户的匿名发布活动已经修改，设置的pcuser_id具有外键约束，因此无法设为空，所以代码的解决方案是设为-1，并在pcuser的表中增加id为-1的项，作为匿名用户。建议如果采用这种方案，最好可以在用户手册中说明，防止以后上线会出现不知名的错误

**Comment by TXZdream** [comment]
完成第三次迭代就关闭issue吧，不然太多会很杂
