### ISSUE TITLE
第一和第二次迭代测试问题反馈

### ISSUE THREAD

**Issue by wuxuemin** [SYSU-ActivityPlusPC/document#11]
## 第一次迭代：发布活动

1. 社团登录：填写完活动信息后，点击【下一步】没反应
2. 匿名登录：应显示用户名[游客]
3. 社团登录：点击进入发布活动，呈现的是【发布成功】页面

## 第二次迭代：数据管理

1. 成功发布的活动没有出现在【活动审核】页面
2. 活动管理：点击切换不同校区的按钮没反应
3. 点击【生成推送】按钮无反应
4. 点击【删除】icon无反应
5. 点击【上下移动】无反应
6. 修改活动信息后：排版出错，刷新后无修改无效
7. 修改活动信息：仅在修改【活动名称】的前提下【提交】按钮才可以点击，应有修改就可以点击
8. 点击【编辑活动信息】，进去后有些必填项为空，例如有的活动地点为空，应：点进去是有原先发布活动时填写的所有的活动信息。

**Comment by wuxuemin** [comment]
## 待优化点
1.	必填：【报名条件】改为【活动对象】
2.	必填：【时间】改为【活动时间】
3.	选填：【活动需求】改为【活动要求】
4.	选填：【通知方式】改为【报名方式】
5.	活动类型增加：户外，休闲，演出
6.	宣传图和二维码成功上传之后要有提示：已成功上传，并提供【删除】按钮，可删除已经上传的图片。
7.	UI: 难以区分是处在【必填】还是【选填】：修改下：选中项字体白色，矩形填充主题色蓝色，非选中项字体白色，矩形填充灰色。与上面的填写流程“填写活动信息“，”等待审核”的类似。
8.	修改文单行和多行编辑框和输入字数限制：
（1）. 采用单行文本编辑框的列表项有：活动名称（限制 30 字以内）
（2）. 采用多行文本编辑框的列表项有：活动地点（100）、活动简介（50），主办方，活动对象，报名方式，活动奖励，活动要求。
每项限制字数括号中所示，没标注括号的不做要求，超过字数有错误提醒
9.	活动时间精确到小时，分钟就可以了

**Comment by Juliiii** [comment]
1、必填：【报名条件】改为【活动对象】✅
2、必填：【时间】改为【活动时间】✅
3、选填：【活动需求】改为【活动要求】✅
4、选填：【通知方式】改为【报名方式】✅
5、活动类型增加：户外，休闲，演出 ✅
6、宣传图和二维码成功上传之后要有提示：已成功上传，并提供【删除】按钮，可删除已经上传的图片。
7、UI: 难以区分是处在【必填】还是【选填】：修改下：选中项字体白色，矩形填充主题色蓝色，非选中项字体白色，矩形填充灰色。与上面的填写流程“填写活动信息“，”等待审核”的类似。✅
8、修改文单行和多行编辑框和输入字数限制：
（1）. 采用单行文本编辑框的列表项有：活动名称（限制 30 字以内）
（2）. 采用多行文本编辑框的列表项有：活动地点（100）、活动简介（50），主办方，活动对象，报名方式，活动奖励，活动要求。
每项限制字数括号中所示，没标注括号的不做要求，超过字数有错误提醒 ✅
8、活动时间精确到小时，分钟就可以了 ✅

**Comment by MichealWind** [comment]
1. 活动管理：点击切换不同校区的按钮没反应 ✅
2.点击【生成推送】按钮无反应 ✅
3.点击【删除】icon无反应 ✅
4.点击【上下移动】无反应 ✅

**Comment by MichealWind** [comment]
## 第一次迭代：发布活动

1、社团登录：填写完活动信息后，点击【下一步】没反应
2、匿名登录：应显示用户名[游客]
3、社团登录：点击进入发布活动，呈现的是【发布成功】页面
## 第二次迭代：数据管理

1、成功发布的活动没有出现在【活动审核】页面
2、活动管理：点击切换不同校区的按钮没反应✅
3、点击【生成推送】按钮无反应✅
4、点击【删除】icon无反应✅
5、点击【上下移动】无反应✅
6、修改活动信息后：排版出错，刷新后无修改无效
7、修改活动信息：仅在修改【活动名称】的前提下【提交】按钮才可以点击，应有修改就可以点击
8、点击【编辑活动信息】，进去后有些必填项为空，例如有的活动地点为空，应：点进去是有原先发布活动时填写的所有的活动信息。

**Comment by wuxuemin** [comment]
- [ ] 成功发布的活动还是没有出现在【活动审核】页面 
@MichealWind

**Comment by MichealWind** [comment]
咦。。我这边测试的有出现呀。。。

**Comment by wuxuemin** [comment]
嗯嗯~可以了,,

**Comment by wuxuemin** [comment]
- [ ] 【活动审核】页面的【通过】审核按钮点击无反应
@MichealWind

**Comment by MichealWind** [comment]
已经解决

**Comment by iamxiaoyubei** [comment]
@wuxuemin 
如果通过测试，请关闭issue

**Comment by wuxuemin** [comment]
- [ ] 审核通过的有图片活动，点击查看活动详情没有显示图片，在生成推送页面中也没有图片 @MichealWind

**Comment by iamxiaoyubei** [comment]
@wuxuemin 
雪敏，以后前端验收测试issue把它开到前端文件夹的issue中去~

**Comment by wuxuemin** [comment]
ok
