### ISSUE TITLE
关于获取的活动信息一些字段缺失的问题

### ISSUE THREAD

**Issue by MichealWind** [SYSU-ActivityPlusPC/document#12]
获取到的活动列表的活动信息中，没有活动的类型type这一字段，导致前端无法根据活动的类型分类生成推送。如果要通过获取活动详细信息这个接口去获取这个字段的话有点冗余，因为这样的话在生成推送时，要对每一个活动都去调用一次接口，开销太大了。所以建议在活动列表返回的字段中加入type这一字段。

**Comment by TXZdream** [comment]
@iamxiaoyubei

**Comment by iamxiaoyubei** [comment]
这个地方我去看了下，发现是我第二次迭代手误删除了type字段，当时测试时没有发现问题，是因为当时前端还没有接上测试，@佳仕，活动列表返回是有type的，我在下一次迭代会把api文档这个纠正，@玄昭，如果说你的api是之前有type的形式，请不用改过来，是我当时手误删了，并不是这一次进行了修改，如果修改了我会提醒你们的，谢谢~
