### ISSUE TITLE
要求：关于文档修改问题

### ISSUE THREAD

**Issue by TXZdream** [SYSU-ActivityPlusPC/document#14]
请求不要在迭代的设计阶段结束后再更改接口，即使发现问题，也希望在回归的时候解决，文档修改之后也不通知前后端人员，api接口是前后端唯一的依据，接口都无法统一，前后端怎么完成对接？

**Comment by iamxiaoyubei** [comment]
亲，这次请你看清楚好吗？我在三天前设计时修改了api文档后就没动过，你看它的记录就知道，技术文档也没改过，就昨天加了个token说明。
在我设计结束之后，才发布的issue，关于旧的API接口需要更改的地方我全部在issue中都提过了。
如果说我修改了api我肯定会在issue上提出来的呀或者通知你们，我也知道你们会不清楚的呀。
所以，请你以后编码之前先仔细看清api文档的属性以及技术文档的描述好吗？
