### ISSUE TITLE
发布活动的API出现问题

### ISSUE THREAD

**Issue by MichealWind** [SYSU-ActivityPlusPC/document#15]
调用发布活动的API和之前调用获取活动列表时一样，在Authorization字段正确的情况下返回了400状态码

**Comment by MichealWind** [comment]
![default](https://user-images.githubusercontent.com/20654931/40297012-e13588b8-5d10-11e8-9791-16d045d64a87.PNG)
这个是调试窗口的截图，如果是传送的数据字段有什么问题的话可以在这和我说明一下

**Comment by TXZdream** [comment]
根据api文档，发布活动的时间格式应为`yyyy-mm-dd hh:mm`而不是毫秒
