### ISSUE TITLE
发布活动API的header加入token说明

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#18]
- Publish a New Activity的API中request header加入了Authorization: token_string，并且属性中**减少了pcuser_id**,请前后端注意。

- Publish a New Activity的技术文档部分进行了增加，后面三条，请前后端注意查看
    - 发布活动API由**前端**控制不同人员发布活动方式不同：匿名登录的话没有可以开启报名，有主办方输入，管理员账号和社团的话，有开启报名选项，呈现主办方输入项，不过主办方默认为该账号主体name，可以进行修改
    - 同时**前端**发布活动时需要**将token放入header中**发送过去(若为匿名发布则token为null即可)
    - **后端**收到请求后,首先校验token获取pcuser_id，若无token则将pcuser_id置为null，生成活动存储到数据库中
    - 注意，**后端**虽然校验token，但是请求未进行拦截，即所有用户均可访问该API

@MichealWind @TXZdream

**Comment by TXZdream** [comment]
现在有一个问题，数据库设计时pcuser_id貌似是外键，有可以设为空的选项吗？

**Comment by iamxiaoyubei** [comment]
设计时是认为可以为空的
相关：[数据库外键可以为空](https://blog.csdn.net/hanghangde/article/details/50487808) and  [mysql外键](https://www.cnblogs.com/musings/p/5913269.html)
