### ISSUE TITLE
第一次迭代API文档(apiblueprint)

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#2]

**Comment by TXZdream** [comment]
emmm，api文档还是可以写写的，不过其他课程我的坑有点多啊，能不能考虑少点任务？关于api文档，建议参考谷歌的rest指南，觉得那个方式定义的接口还是比较清楚的，现有的api从某种程度上来说，不太好扩展的感觉，可以考虑在完成代码之后进行重构

**Comment by iamxiaoyubei** [comment]
这个任务不是你的，API文档已经写了，就是apiary，只是如果你在写代码的时候有多的HTTP code补充和解释，需要在API和技术文档里面添加补充。
