### ISSUE TITLE
配置文件

### ISSUE THREAD

**Issue by TXZdream** [SYSU-ActivityPlusPC/document#20]
@iamxiaoyubei  针对私密信息问题，建议将相关信息存储在文件中，例如json格式或者yml格式的文件，具体格式自定，建议现在开始定义字段，之后再进行修改成本也不大，例如：加密密钥、这次迭代可能出现的发送邮件的邮箱账号密码等

**Comment by iamxiaoyubei** [comment]
用户名密码这些都是内部流通，不太懂你说的意思？

**Comment by TXZdream** [comment]
但是编写代码是需要用到的……即使内部使用，也是要记录下来吧

**Comment by iamxiaoyubei** [comment]
ok，我知道了
