### ISSUE TITLE
第四次迭代技术文档和API文档反馈

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#22]
@MichealWind 
@TXZdream 
请仔细查看第四次迭代文档和API，于5月29日晚23：00前提出问题，之后基本确定文档，然后再进行开发，在开发中基本只会对文档进行很小的修改，会于issue中提出。

**Comment by TXZdream** [comment]
1. 获取pc用户信息中的密码无任何意义，因为是已经反复加密之后的字符串
2. 同1接口，pubActivity指的是该用户发布的所有活动？想知道设计目的
3. 审查用户账户接口中，对于后台的具体技术细节描述过于模糊，希望增加例如：是否异步？如何实现异步之类，这些也是我想了解的
4. 同上接口，希望直接在接口加上body，用以告知未通过原因，这样就可以通过邮件一并发送了
5. 获取注册详情是返回所有的用户还是只有未通过的用户？
6. 获取注册详情和社团信息的接口可以通过传参的方式合成一个，如不需要特别区分，没必要写两次几乎一样的接口
7. 文档中的最后一个接口是为了给社团获得消息详情还是管理员？

话说这次迭代多长时间，8个接口真的没关系？

**Comment by iamxiaoyubei** [comment]
@wuxuemin 请回答一下1，2问题
1. 获取pc用户信息中的密码无任何意义，因为是已经反复加密之后的字符串，所以需求这个是否可以去掉？
2. 玄昭第二个问题
3. 审核里面存在的一个未知问题应该就是发送信息到邮箱，这个可以调用go里面自带的[smtp包来发送邮件](http://outofmemory.cn/code-snippet/580/go-language-send-youjian-code)，[另个例子](https://blog.csdn.net/liang19890820/article/details/53084638)或者github中找其他的包来发送邮件，如[使用goemail](https://blog.csdn.net/idwtwt/article/details/51913249)，应该不会很难，你说的异步是指？为何考虑到异步？
4. 你是说拒绝的时候也使用邮箱发送拒绝信息？这个要
@wuxuemin ，对于第四个问题，需求的考虑
5. 注册详情API和社团信息API是同一个API，注册详情查看待审核和已拒绝活动列表，社团信息查看查看已经通过审核的社团列表，所以实际上该API可以返回任意类型的活动，我只是分开描述，这个只是根据id来返回活动，请再看一下技术文档
6. 同上，是一个接口，其实我也可以在一起描述啦，只是写的时候分开写了
7. 这次的API都是管理员权限，我们暂时先不考虑社团的通知功能部分，太多了
8. 邮箱在问题3进行了说明，请查看
9. 这次后端我和你一起做，等技术文档确定后再分工，目前先别着急写

**Comment by TXZdream** [comment]
1. 关于异步邮件发送问题：即使用rebbitmq，利用消息队列完成异步方式的邮件发送，新增一个项目，用来作为消息队列的接收和处理，服务端收到请求，则发送消息到消息队列，完成后立即返回请求，减少等待时间

**Comment by wuxuemin** [comment]
1. 综合考虑了使用的便利性，社团信息列表更新为：社团名称+账号（即为联系邮箱）+注册时间+组织logo+证明材料。为了便于社团使用，社团首次注册成功后将登录的账号密码发送至社团注册时填写的联系邮箱中，暂时先不做社团信息修改，社团忘记密码时通过联系邮箱进行验证，填写新密码，成功后将账号和新密码发送至邮箱
2. 1中已说明
3. 第四的问题，可进行一并发送
4. 关于邮箱，可以使用中大活动的一个申请的一个163邮箱作为系统自动发送邮件的发送方吗

**Comment by iamxiaoyubei** [comment]
@TXZdream  注意一下：账号默认为该社团的联系邮箱，且email设置为了unique，且需要在注册时候添加一下检查邮箱是否重复

**Comment by TXZdream** [comment]
邮箱我通过腾讯企业邮进行了注册，发送方会以`admin@sysuactivity.com`的身份实施

**Comment by TXZdream** [comment]
审计用户的body字段在数据库中并没有可以存放的地方

**Comment by TXZdream** [comment]
@iamxiaoyubei 获取社团列表，要求按照处理的顺序先后排序，然而在数据库中并没有记录处理的时间，因此该要求无法实现，当前的实现方式为按照时间进行排序

**Comment by iamxiaoyubei** [comment]
@TXZdream 
1. 审计用户的body无需进行存储，拒绝信息只需要通过邮件发送过去，不需要在数据库中保存
2. 处理时间也是保存在register_time中，待审核的活动无论是通过审核还是拒绝，都将register_time更新为审核注册处理时的时间。

**Comment by TXZdream** [comment]
话说前一个问题我删除了哎，还能看到？
