### ISSUE TITLE
社团活动管理中活动列表的“活动发布时间”

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#29]
社团活动管理中活动列表的“活动发布时间”是哪个时间？
开始时间有：starttime活动开始时间，pubstarttime活动宣传开始时间
活动发布时间可否为pubstarttime？

**Comment by wuxuemin** [comment]
就是社团点击提交的发布活动信息的时间,这个时间有记录吗?

**Comment by iamxiaoyubei** [comment]
？是说社团点击发布活动时，那时候的时间？
还是说 社团填写的活动宣传开始时间？即在我们小程序上开始呈现的时间

**Comment by wuxuemin** [comment]
？是说社团点击发布活动时，那时候的时间？

对

**Comment by iamxiaoyubei** [comment]
可不可以直接 社团填写的活动宣传开始时间即在我们小程序上开始呈现的时间 呀
以为活动这个对象里面的时间信息已经很多了，我觉得这么多时间太繁琐了，也没有必要

**Comment by iamxiaoyubei** [comment]
而且我觉得 “活动宣传开始时间” 更为有价值诶
活动列表那里 改为 ********开始宣传，这样的话，感觉对于社团来说，得到的信息更有价值，你觉得呢

**Comment by wuxuemin** [comment]
太多项的时间的话可以用现有的宣传时间吧

**Comment by iamxiaoyubei** [comment]
好的，那就用活动宣传开始时间
雪敏，那需求文档 活动列表那里 改为 ********开始宣传 这样吧？
