### ISSUE TITLE
未通过审核的活动是否会在活动列表中呈现

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#31]
1. 未通过审核的活动是否会在活动列表中呈现
2. 若呈现，状态是？未通过审核？是否应该是三个字2333
3. 那鼠标放到活动管理那里，是否也要呈现**个活动未审核通过

**Comment by wuxuemin** [comment]
无需呈现未通过审核

**Comment by wuxuemin** [comment]
没有通过审核的就邮件告知就可以了,社团知道没通过再重新发布就ok,活动列表是主要是查看正在进行的活动的动态.
