### ISSUE TITLE
部分涉及到小程序端的修改

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#32]
部分涉及到小程序端的修改：
1. 报名在小程序端的结束显示
2. 报名的 可报名和未开启报名
3. 报名的表格的填写选项
4. 报名的填写时间
这些会涉及到小程序的更改，后期再和小程序端商议，进行相应的更改

**Comment by iamxiaoyubei** [comment]
5. 报名表中应该要含有actapplyid

**Comment by iamxiaoyubei** [comment]
点击【结束报名】按钮，对应生成的报名链接失效或链接到注明【该活动已结束报名，感谢支持】的页面。

**Comment by TXZdream** [comment]
4. 报名的填写时间貌似有了？还是我记错了？
5. 对于每一个活动申请，已经加入了id，但是有一个问题，原先的活动是以报名者学号和活动id唯一区分的，现在以报名id唯一区分，感觉会存在重复报名的情况

顺便一提，感觉现在所有的数据都是以id为主键，也就是说，一个完全相同的信息可以被成功提交很多次，所以想是不是应该在技术文档中，明确一下具体的每个表或者条目的区分依据？
