### ISSUE TITLE
第五次需求文档，技术文档，API反馈

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#34]
目前需要实现的部分，需求文档，技术文档，API已完成；至于报名部分，存在一部分需要与小程序团队协调的问题，这些问题先不考虑，协调后再加上。
大家先看目前的文档，是否存在什么问题或疑惑或建议，请提出来~谢谢~

**Comment by TXZdream** [comment]
1. List required activities By Club返回的是通过审核的活动，那问题在于审核中算是审核通过吗？
2. 作为活动发布者，为什么会没有查看自己发布的活动，即使它没有通过审核？
3. emmm，甩个锅，小程序后面就是修修补补的工作了，新的需求不再实现了，具体可以找老板商议
4. 所有仅社团可访问权限是否包括管理员
5. 小程序端没有储存每个活动的浏览次数哦~也就是说，pageviews没办法获得的

最后关于接口测试的问题，所有涉及数据库修改的接口，如果修改的某个字段的值可能为0时，一定要注意对照数据库检查是否有误，因为xorm会默认不更新空的值，也就是说，可能最后并没有进行数据库更新，解决方法是用cols字段说明或者用map进行更新，当前为了偷懒，使用了前者，但是难免存在疏忽，所以一定注意！！！

**Comment by iamxiaoyubei** [comment]
1. 仅返回未被拒绝的活动，无需呈现审核被拒绝的活动
2. 同上，只有审核被拒绝的活动看不了，其他在列表中均有
3. 活动报名那里还有许多需要修补的，这应该是个重要的功能，先把当前迭代完成后，再找他商议
4. 不包括，管理员可以访问的在文档中也有说明
5. 不是活动，而是某个活动的活动详情页面，因此通过调用小程序API，获取该活动的小程序页面的浏览数返回，按理来说应该有这样的API的，昨天我查了一下，网上说可以，不过目前还没有查到具体的API，这个需要实现的时候，细致查询完成了，如果说真的找不到这个API的话，那就先把pageViews默认填上一个数值返回先
6. 没太懂你说的最后的那个是什么意思；这次数据库的内部没有变动的地方，actApply表格在之前已经有了，只是PC端还没有显示给大家看，然后can_enrolled增加一个2的意思是，告诉你们用2来表达结束报名，can_enrolled本就是一个int，可以为2，只是我们多了一个2的解释和可以取为2，如此。所以你说的是啥意思？没太懂，请再解释一下谢谢。

**Comment by TXZdream** [comment]
*1. 你没有get到我的问题点，那就是我想问的是：审批中的活动应该不算被拒绝吧？当然，我现在应该知道答案了
*2. 同样的，我想知道一下设计意图，就是为什么看不到没有通过审核的活动
*5. 希望可以查到一下相关的接口并放到技术文档中，最近两周都很忙，不一定有时间去管这个
*6. 这个问题是普遍存在的，不一定指的是这次迭代，只是提醒注意一下，和具体数据库设计没有关系，只是代码问题，让你注意一下，当需要修改的值为默认值时，例如：需要修改一个类型为int，值为0的字段时，很有可能无法完成修改

以上，顺便提一下，总觉得你上面回复优点抓不住重点？如果最近太忙记得注意休息。

**Comment by iamxiaoyubei** [comment]
1. 我get到你的点了，只是以一种更全面的方式来回答了，而不是只说你的点，审核中的活动当然不算是被拒绝审核的，我知道你最开始的意思是问“审核中”的活动算是“未通过审核”的活动吗？因为我最开始文档中没写清楚，写的是“未通过审核”，而不是“审核被拒绝”；我觉得“审核被拒绝”已经代表比较清晰了，故没有指出。
2. 这个问题我也是存在着疑惑的，所以我也问了雪敏 #31 ，看不到的只是审核被拒绝的活动，如果还有需求设计上的问题，可以问 @wuxuemin 
5. 按理来说，某些细致的工作难道不是编码的时候做的吗？就比如API的查询......我会查到，查到会加上去，没查到就算了，按照我上面说的继续做
6. 我的意思是确实没看懂你说的...它是普遍存在的问题我也听不太懂...什么需要修改一个类型为int，值为0的字段时，很有可能无法完成修改？？修改成啥？为啥无法完成修改？

我觉得可能你没有get到我答案的点吧，emmm...... 每个人思考得时候想得方向不一样，很正常~以后我会跟你说的一样回答到你的点的。

**Comment by iamxiaoyubei** [comment]
还有什么问题吗？请尽快指出来，就要分工了，之前看你们对回复没啥反应，所以还没进行分工。如果今天中午之前没有回应我就确定默认OK了哦~

**Comment by TXZdream** [comment]
关于最后一个问题吧，就是关于数据库更新的那个，给你一个链接，你看一下，应该比我说的好理解一些，就是xorm文档的``update records`那里，看一下应该可以理解我指出的问题的，还算比较严重；

关于技术问题的话，因为你说微信文档有，所以大概意思是希望可以把链接回复发一下，因为不是很理解这个。

因为还没写，所以先问一下，你那边权限验证是在哪里进行的？如果是在业务代码中完成的，那我可能在写代码的时候把权限验证统一到中间件中，如果在中间件中，那就没其他问题了。

这两天的话，就是周五到周日，一直没怎么干活，所以拖到现在，还请见谅。

**Comment by iamxiaoyubei** [comment]
1. Got it.
2. 链接发了哈，在一个issue中提到，并且目前打算不做这个工作了，具体可以看 #36 ，同时这个功能这次不是你的迭代任务，不用担心
3. 中间件的，差不多在最后面几行
