### ISSUE TITLE
欠缺的必要功能点

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#35]
检查看下有些什么欠缺的必要功能点，先列在这个issue下面，我会视情况考量是否要补上。

**Comment by wuxuemin** [comment]
活动浏览量移入以后的数据分析

**Comment by wuxuemin** [comment]
PC:

1. 审核通过的有图片活动，点击查看活动详情没有显示图片，在生成推送页面中也没有图片

**Comment by iamxiaoyubei** [comment]
修改密码以及社团查看通知API
发布活动时的，报名活动的开启和关闭，以及自定义选项的确认

**Comment by wuxuemin** [comment]
PC:活动到了报名截止时间或者到了活动宣传时间后，在管理员页面的活动列表页面自动将活动删除

**Comment by wuxuemin** [comment]
忘记密码

**Comment by TXZdream** [comment]
1. 活动状态检查。即根据时间自动进行活动状态的修改
2. 用户注册界面，tab键和回车键的支持
3. 新活动提醒、新消息提醒

**Comment by TXZdream** [comment]
提一下，现在的系统还有一个大问题，就在于没有机器人防治措施，例如图形验证码之类的方法；另外，前端的所有信息都是明文传输的，例如用户密码，是不是考虑加密一下？即前端加密，虽然没什么用，但是总比直接把明文密码暴露出来要好吧。
