### ISSUE TITLE
一些需求的疑问

### ISSUE THREAD

**Issue by MichealWind** [SYSU-ActivityPlusPC/document#39]
关于管理员模块中的注册申请页面，
![image](https://user-images.githubusercontent.com/20654931/41809341-9cdfaf5e-771e-11e8-9225-f426aeace6e6.png)
已经通过的社团是否可以再次进行注册审核呢？如果不用的话在这里是不是不要渲染已通过的社团比较好？

**Comment by wuxuemin** [comment]
上面图片的页面上不需要有已通过的社团,需求文档的补充说明文字部分已有说明.
上图只需2个列表:先排列【待审核】列表（按照申请的时间先后顺序），之后排列【已拒绝】列表（按照处理的时间先后顺序）
