### ISSUE TITLE
最终文档撰写

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#40]
- [x] 安装部署说明： @TXZdream 完成，若需要前端的安装说明，则由 @MichealWind @Juliiii 协助完成这部分

- [x] 用户使用手册： @wuxuemin 完成

- [x] 软件需求规格说明书： @wuxuemin 完成

- [x] 软件设计文档： @iamxiaoyubei 完成 @TXZdream 协助完成部分(之后会指定) @MichealWind @Juliiii 协助完成前端的部分(之后会指定)

- [x] 小组分工与贡献率说明： @iamxiaoyubei 完成

文档参考：
https://github.com/SevenDwarfs/BookingSystem
https://github.com/SYSUMonkeyEye/MonkeyEye-Doc

文档要求：在document目录下的Syllabus.pdf的P10-P11

文档已经新建在document目录下了，直接在其中添加写入即可，注意是markdown格式

**DDL**：6月28日完成最终版本

**Comment by TXZdream** [comment]
@iamxiaoyubei 完成安装部署说明文档编写，请检查是否有需要补充部分
