### ISSUE TITLE
关于安装部署说明文档的问题

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#41]
最后一行：完成后，浏览器打开管理端即可进入产品的前端页面

1. 在本地部署，应该是打开本地的一个连接
2. 之后再稍微说明一下，按照以上方法，我们将我们的产品部署到了腾讯云服务器，然后就通过 “浏览器打开管理端即可进入产品的前端页面” 网页的那个就可以进入前端

**Comment by TXZdream** [comment]
不建议本地部署吧，ssl的域名不匹配会出错的，还是直接说在云端部署吧
