### ISSUE TITLE
04_软件设计文档分工

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/document#43]
请看document目录下的 04_软件设计文档分工，分工里面有标名字

- [x] 理锋完成**前端**中的 技术选型及理由 和 架构设计

- [x] 佳仕完成**前端**中的 模块划分 和 软件设计技术

- [x] 玄昭完成**后端**中的 技术选型及理由 和 软件设计技术

- [x]  预备完成其他all

@MichealWind @Juliiii @TXZdream 今晚完成初稿可否？或明中午之前？

**Comment by iamxiaoyubei** [comment]
参考 https://github.com/SYSUMonkeyEye/MonkeyEye-Doc/blob/master/%E8%BD%AF%E4%BB%B6%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3.md

**Comment by iamxiaoyubei** [comment]
且需要注意 Syllabus P11 P16的要求

**Comment by TXZdream** [comment]
最后要求贴上来一下吧
