### ISSUE TITLE
问题：数据库字段

### ISSUE THREAD

**Issue by TXZdream** [SYSU-ActivityPlusPC/document#7]
注意到文档中数据库字段中含有binary属性，这里极其不建议使用该属性，建议修改为int类型，如果使用该类型，以我知识水平还不是很清楚如何才能进行解析

**Comment by TXZdream** [comment]
补充：数据库中的文件名字段过短，除需要文件名之外，扩展名也应该计算在内，因此，只有64位过短，建议增长成70位

**Comment by iamxiaoyubei** [comment]
1.查看之前你的verified数据库er表设置的是binary，在数据库中你使用的是int？
2.已改为70位

**Comment by iamxiaoyubei** [comment]
已修改，请继续查看是否有什么其他问题~

**Comment by TXZdream** [comment]
数据库字段之前的已经修改成int，可能文件还未修改

**Comment by TXZdream** [comment]
文档未指明后台代码加密方式，默认使用用户名作为盐值，使用aes加密

**Comment by TXZdream** [comment]
数据库的id应有`AUTO_INCREMENT`这一属性，否则后台代码的自增无法生效
