### ISSUE TITLE
问题：文件上传api

### ISSUE THREAD

**Issue by TXZdream** [SYSU-ActivityPlusPC/document#8]
文件上传貌似必须通过表单的方式解决，因此必须要前端实现一个表单，后台对表单进行解析，获取文件内容，这里默认使用`files`作为后台文件解析字段

**Comment by TXZdream** [comment]
https://github.com/astaxie/build-web-application-with-golang/blob/master/zh/04.5.md

**Comment by iamxiaoyubei** [comment]
OK

**Comment by iamxiaoyubei** [comment]
content-type为multipart/form-data
表单name为file, 类型为file,将图片文件上传

**Comment by TXZdream** [comment]
后台没有进行文件合法性检查，麻烦你加一个issue要求一下后台的图片类型检查？
其余ok
